### ISSUE TITLE
Could vertical menu appear without clicking on collapse button?

### ISSUE THREAD

**Issue by rm450** [adnantopal/slimmenu#22]
First off, great menu! I've looked at a bunch and went with this one.

Now, I want to customize it a bit.... I have a small main menu (with a bunch of sub menus) and don't want the collapse button to ever appear. Is there a way to make the vertical menu always appear once the right width is reached, without showing (and then clicking on) the collapse button?

Thanks for any help you can provide!

**Comment by adnantopal** [comment]
See newly added option `initiallyVisible`.
