### ISSUE TITLE
Child menu not visible when we resize the browser window

### ISSUE THREAD

**Issue by KarthikDev81** [adnantopal/slimmenu#26]
Hi,

When we resize the browser window (Click Slim Menu --> Slim Menu 1.1 --> Slim Menu 1.1.1), the child menu will go under the "Slim Menu 2"
![01](https://cloud.githubusercontent.com/assets/7814711/3199368/78fbc4aa-ed67-11e3-86d5-0e11f4710023.jpg)
![02](https://cloud.githubusercontent.com/assets/7814711/3199369/78fc4268-ed67-11e3-9a73-d094c45ef109.jpg)
![03](https://cloud.githubusercontent.com/assets/7814711/3199370/79034b08-ed67-11e3-8a5a-e4bec65626e4.jpg)
![04](https://cloud.githubusercontent.com/assets/7814711/3199371/790418d0-ed67-11e3-9874-427e2f49307f.jpg)

**Comment by guilmanu** [comment]
+1 : SLIM Menu works fine …until the window is resized : submenus become invisible when hovering first level items !

**Comment by KarthikDev81** [comment]
Thanks for the notification :)
