### ISSUE TITLE
Slim menu bug on android chrome browser 

### ISSUE THREAD

**Issue by Mahaaveer** [adnantopal/slimmenu#35]
Slim menu collapses back onto the menu if page is scrolled down on  Android Chrome browser. it makes the navigation impossible if i have long list of submenus.

it works fine on native android browser. i tested on different devices.

Please resolve the issue.

**Comment by DivaVocals** [comment]
I have noticed that this issue is still present.. Is there a solution for this??

**Comment by titusvk** [comment]
I think the problem is, the jQuery hover action and the jQuery click event activates to open and close. Someone should recode the events. Why not use jQuery mobile?

**Comment by DivaVocals** [comment]
Solutions summary here:
https://github.com/adnantopal/slimmenu/issues/43
