### ISSUE TITLE
Not working properly in IE11

### ISSUE THREAD

**Issue by zaans2** [adnantopal/slimmenu#39]
I have have everything set up like and it works beautifully in Chrome, Firefox, etc. But the ancient piece of software called Internet Explorer gives me a script error. it says 'this property or method isn't supported by the object' and then it just simply doesn't do anything.
 Note: I've implemented it in a WordPress Theme, so there could be an issue there but I have no idea where it lies.

**Comment by harjinderkamboj** [comment]
Try forcing it to run in compatible mode by putting following meta tag in the <head> section:

<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
