### ISSUE TITLE
Menu Collapses on Scroll Issue - Will an update make it's way into the master repo??

### ISSUE THREAD

**Issue by DivaVocals** [adnantopal/slimmenu#43]
This menu code hasn't been updated since 2013. However there is a bug with how this menu behaves on Android and older iOS devices. In short, the slim menu closes every time the page is scrolled.

The issue is reported here:
#41, #38, #27, #21 (issues where the problem is reported)

There are two pull requests which are supposed to address the issue: #28 - July 2014, #38 - Nov, 2014 (pull requests that APPEAR to address the menu collapse issue)

I have tested both solutions.. Both work, but I am not clear as to which ONE of these solutions is the correct/right solution. The question now is will this repo be updated with one or the other or yet another (working) solution. 

Because the code in the master repo is UNUSABLE for Android devices, and because there are template designers using this menu who may not have BOTHERED to see if a solution for this issue exists, I wanted to summarize the problem, link it to other reports, and finally post solutions for those who come to this repo looking for answers to this issue.

**Comment by vinylroads** [comment]
I agree with you. Slimemenu is a great plugin. It would be nice if the author could update the plugin.

For me, the commit by dusty73 works : https://github.com/adnantopal/slimmenu/pull/38

**Comment by DivaVocals** [comment]
:+1:
