### ISSUE TITLE
Change font-size when collapsed (smartphone)

### ISSUE THREAD

**Issue by MN83GH** [adnantopal/slimmenu#44]
Hi! 

I wonder if it's possible to change font-size, only when you are in smartphone mode (320 to 800px)

Any tips or tutorial?

Thank you guys

**Comment by designarti** [comment]
Thats a CSS issue and could be solved by adding a media query into your css file, usually at the end:
```
media all and (max-width: 800px) {
    ul.slimmenu li {
        font-size: 14px;
    }
}
```
This is probably what you need.
