### ISSUE TITLE
slimmenu doesn't fit at same line with more than 5 parent li in first ul

### ISSUE THREAD

**Issue by irun4ik** [adnantopal/slimmenu#48]
The slimmenu doesn't fit at same line (not responsive enough) with more than 5 parent li in first ul. Is there a solution to this?

**Comment by desertlavender** [comment]
I had this problem but resolved it by using CSS to change the font size and right padding of the menu items as well as the font size, width and right margin of the subcollapser. Now easily fitting six menu items even on an iPad at mirasol.net.  Thanks adnantopal for the great work!
