### ISSUE TITLE
Menu disapear while scrolling

### ISSUE THREAD

**Issue by mathishuettl** [adnantopal/slimmenu#52]
Hello, im using slimmenu, but when the menu is open and i scroll down, it disapears... but just with mobile safari - do you have a solution for me?

http://brixner.ep-vorschau.at/

regards

**Comment by HasiSteinbeiss** [comment]
I love this menu very much but i have the same Problem. Any solutions would be great!!

**Comment by ralbion** [comment]
Hi, 
I'm out of the office until July 20th.I will be checking email fairly regularly in the meantime. Any matter I consider to be genuinely urgent will be attended to as soon as possible.Enjoy your summer,Rich

Richard AlbionWeb Design and DevelopmentSearch Engine Marketing
www.richardalbion.com
mail@richardalbion.com
+1 508 3403880 (USA)
+44 (0)207 1938229 (UK)--

**Comment by jasonc310771** [comment]
HI,  I have been looking for this type of menu and so far all looks good apart from this scrolling issue.  From what I hear it is mainly the Iphone that the issue shows itself.  You click the collapse-button and the menu opens, if the menu has more items that the page height allows you have to scroll the page up to get the the items further down the menu.  When you touch the screen to scroll up the menu dissapears.  Preventing you you from going to the page you want.

**Comment by BuildMyWeb** [comment]
this is not an issue exclusive to safari.  or iphone.  and i dont think it technically a bug.  i think it was an intended feature.  but as jasonc310771 explained, very well, it is problematic when you have to scroll down a page to get at a menu item and the menu collapses.

**Comment by ralbion** [comment]
Hi, 
I'm out of the office until August 21st.Regards,Rich

Richard AlbionWeb Design and DevelopmentSearch Engine Marketing
www.richardalbion.com
mail@richardalbion.com
+1 508 3403880 (USA)
+44 (0)207 1938229 (UK)--

**Comment by bakkers12** [comment]
Hello

Has anyone found a solution to this, i have this problem in both iphone and andorid. I found out that it's happening when the adresse bar in either andorid or iphone hides the menu also closes.

Regards
Thomas

**Comment by jasonc310771** [comment]
https://github.com/dusty73/slimmenu/commit/70d5c15bdbefeb2bad8f96d6387719c88b84d1e6
